### ISSUE TITLE
Update to support newer version of Ulauncher

### ISSUE THREAD

**Issue by Hedronmx** [brpaz/ulauncher-text-expander#7]
Please make this usable on newer versions of Ulauncher.

**Comment by sWoifal** [comment]
+1 Yes, please. That would be very nice!

**Comment by sWoifal** [comment]
The extension was updated, but it keeps crashing (other updated extensions from the same author seem to work though). When launching ulauncher from command line i see "ModuleNotFoundError: No module named 'glob2'" but pip package glob2 is installed.

**Comment by riteshsahu314** [comment]
Yes it works! Thank You.

**Comment by brpaz** [comment]
Python has it´s dependencies ;(

Have some troubles setup on a new machine.
